{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.attic;
  clientPkg = pkgs.attic-client;
  serverPkg = pkgs.attic-server;
  serverPort = lib.toInt (lib.last (lib.splitString ":" cfg.server.listen));
  # Generate the same TOML config that services.atticd uses, so we can call
  # atticadm directly with a store path instead of relying on the module's
  # atticd-atticadm wrapper at runtime.
  atticConfigFormat = pkgs.formats.toml { };
  atticConfigFile = atticConfigFormat.generate "attic-server.toml" config.services.atticd.settings;
in
{
  options.attic = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Enable the Attic binary cache client: adds the server as a Nix
        substituter (once `cachePublicKey` is set) and automatically pushes the
        current system's closure to the cache on every rebuild. Set to false to
        opt out on a particular machine.
      '';
    };

    serverEndpoint = lib.mkOption {
      type = lib.types.str;
      default = "http://localhost:8080";
      description = ''
        URL of the Attic server to push to and pull from. Defaults to
        localhost, which only works on the machine running the server. On
        client machines, set this to the server's address (e.g.
        `http://dosa:8080` over Tailscale).
      '';
    };

    cacheName = lib.mkOption {
      type = lib.types.str;
      default = "nix-cache";
      description = ''
        Name of the Attic cache to push to and pull from. Create it on the
        server with `attic cache create --public <name>`.
      '';
    };

    cachePublicKey = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "nix-cache:wYLWwiQLitp+BNv8uAAp2ieTveH0lniKAMSmjsWsnuM=";
      description = ''
        Public key of the Attic cache (e.g. `nixos:AAAA...==`), needed for Nix
        to trust paths pulled from the cache. Obtain it once after creating the
        cache (`attic use <cache>` prints it, or `attic cache info <cache>`)
        and set it here. Until then pushes work but pulls are not trusted.
      '';
    };

    tokenFile = lib.mkOption {
      type = lib.types.str;
      default = if cfg.server.enable then "/var/lib/atticd/push-token" else "/etc/attic/attic-token";
      defaultText = "/etc/attic/attic-token";
      description = ''
        Path to a file containing an Attic push token. On the server machine,
        this defaults to the token generated by the `attic-bootstrap` script at
        `/var/lib/atticd/push-token`. On client machines, create the file
        out-of-band, e.g.:

          install -m600 -o root -g root /dev/null /etc/attic/attic-token
          echo -n '<token>' > /etc/attic/attic-token
      '';
    };

    server = {
      enable = lib.mkEnableOption "the Attic server (atticd) on this machine";

      listen = lib.mkOption {
        type = lib.types.str;
        default = "0.0.0.0:8080";
        description = ''
          Address and port for atticd to listen on.
        '';
      };

      openFirewall = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Open the firewall for the atticd listen port.
        '';
      };

      bootstrap = {
        tokenValidity = lib.mkOption {
          type = lib.types.str;
          default = "10y";
          description = ''
            Validity period for the push token generated by the
            `attic-bootstrap` script (e.g. "10y", "2 years", "6 months").
          '';
        };
      };
    };
  };

  config = lib.mkIf cfg.enable (
    lib.mkMerge [
      {
        environment.systemPackages = [ clientPkg ];

        nix.settings = {
          substituters = [ cfg.serverEndpoint ];
        }
        // (lib.optionalAttrs (cfg.cachePublicKey != null) {
          trusted-public-keys = [ cfg.cachePublicKey ];
        });

        systemd.services.attic-push-system = {
          description = "Push the current NixOS system closure to the Attic cache";
          after = [ "network-online.target" ];
          wants = [ "network-online.target" ];
          wantedBy = [ "multi-user.target" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            Environment = [ "HOME=/root" ];
          };
          script = ''
            if [ ! -f "${cfg.tokenFile}" ]; then
              echo "attic-push-system: token file ${cfg.tokenFile} not found; skipping push." >&2
              exit 0
            fi

            TOKEN="$(cat "${cfg.tokenFile}")"
            if [ -z "$TOKEN" ]; then
              echo "attic-push-system: token file is empty; skipping push." >&2
              exit 0
            fi

            ${lib.getExe clientPkg} login --set-default local "${cfg.serverEndpoint}" "$TOKEN"
            echo "attic-push-system: pushing system closure to cache '${cfg.cacheName}'..."
            ${lib.getExe clientPkg} push "${cfg.cacheName}" /run/current-system
          '';
        };

        # Watch /run/current-system (updated by nixos-rebuild switch) and
        # trigger a push whenever a new generation is activated. This avoids
        # referencing config.system.build.toplevel at eval time, which would
        # cause an infinite recursion (toplevel depends on this unit's script).
        systemd.paths.attic-push-system = {
          description = "Watch for NixOS generation changes to trigger Attic push";
          wantedBy = [ "multi-user.target" ];
          pathConfig.PathChanged = "/run/current-system";
        };
      }

      (lib.mkIf cfg.server.enable {
        services.atticd = {
          enable = true;
          environmentFile = "/var/lib/attic-secrets/env";
          settings = {
            listen = cfg.server.listen;
            database.url = "sqlite:///var/lib/atticd/server.db?mode=rwc";
            storage = {
              type = "local";
              path = "/var/lib/atticd/storage";
            };
            chunking = {
              nar-size-threshold = 65536;
              min-size = 16384;
              avg-size = 65536;
              max-size = 262144;
            };
          };
        };

        # Generate the RS256 JWT signing secret once and persist it, so tokens
        # stay valid across reboots. EnvironmentFile= is read by systemd (as
        # root), so a root-owned 0600 file outside atticd's state dir works
        # regardless of atticd's DynamicUser sandboxing.
        systemd.services.atticd-gen-secret = {
          description = "Generate the atticd RS256 JWT secret if missing";
          before = [ "atticd.service" ];
          requiredBy = [ "atticd.service" ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          script = ''
            mkdir -p /var/lib/attic-secrets
            if [ ! -f /var/lib/attic-secrets/env ]; then
              echo "atticd-gen-secret: generating new RS256 secret..."
              SECRET="$(${lib.getExe' pkgs.openssl "openssl"} genrsa -traditional 4096 | ${lib.getExe' pkgs.coreutils "base64"} -w0)"
              printf 'ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64=%s\n' "$SECRET" > /var/lib/attic-secrets/env
              chmod 600 /var/lib/attic-secrets/env
            fi
          '';
        };

        # Script to bootstrap the cache and generate a push token. Run
        # manually after atticd is up: `sudo attic-bootstrap`.
        # Idempotent — skips creation if the cache and token already exist.
        environment.systemPackages = [
          (pkgs.writeShellScriptBin "attic-bootstrap" ''
            set -e

            if [ ! -f /var/lib/attic-secrets/env ]; then
              echo "attic-bootstrap: JWT secret not found at /var/lib/attic-secrets/env" >&2
              echo "attic-bootstrap: is atticd-gen-secret running? Run 'systemctl start atticd-gen-secret' first." >&2
              exit 1
            fi

            # Generate a push token (idempotent: reuse if already exists)
            TOKEN_FILE="${cfg.tokenFile}"
            mkdir -p "$(dirname "$TOKEN_FILE")"

            if [ -s "$TOKEN_FILE" ]; then
              echo "attic-bootstrap: token file already exists, reusing."
              TOKEN="$(cat "$TOKEN_FILE")"
            else
              echo "attic-bootstrap: generating new push token (validity: ${cfg.server.bootstrap.tokenValidity})..."
              # Load the JWT signing secret that atticd-gen-secret created
              set -a
              . /var/lib/attic-secrets/env
              set +a
              TOKEN="$(${lib.getExe' serverPkg "atticadm"} -f ${atticConfigFile} make-token \
                --sub "auto-bootstrap" \
                --validity "${cfg.server.bootstrap.tokenValidity}" \
                --pull "*" \
                --push "*" \
                --create-cache "*" \
                --configure-cache "*" \
              )"
              printf '%s' "$TOKEN" > "$TOKEN_FILE"
              chmod 600 "$TOKEN_FILE"
              echo "attic-bootstrap: token written to $TOKEN_FILE"
            fi

            # Login with the token (as root, for cache creation)
            ${lib.getExe clientPkg} login --set-default local "${cfg.serverEndpoint}" "$TOKEN"

            # Create the cache if it doesn't exist
            if ${lib.getExe clientPkg} cache info "${cfg.cacheName}" 2>/dev/null; then
              echo "attic-bootstrap: cache '${cfg.cacheName}' already exists."
            else
              echo "attic-bootstrap: creating public cache '${cfg.cacheName}'..."
              ${lib.getExe clientPkg} cache create --public "${cfg.cacheName}"
              echo "attic-bootstrap: cache created."
            fi

            # Extract and save the public key
            mkdir -p /var/lib/atticd
            PUBKEY="$(${lib.getExe clientPkg} cache info "${cfg.cacheName}" 2>/dev/null | ${lib.getExe' pkgs.gnugrep "grep"} -oP 'Public Key:\s*\K.*' || true)"
            if [ -n "$PUBKEY" ]; then
              printf '%s\n' "$PUBKEY" > /var/lib/atticd/cache-pubkey
              chmod 644 /var/lib/atticd/cache-pubkey
              echo "attic-bootstrap: public key: $PUBKEY"
              echo "attic-bootstrap: public key saved to /var/lib/atticd/cache-pubkey"
              echo "attic-bootstrap: >>> Set attic.cachePublicKey = \"$PUBKEY\"; in your config to enable pulling. <<<"
            fi

            # Print the token for distribution to client machines
            echo "attic-bootstrap: >>> To set up client machines, copy this token to ${cfg.tokenFile} on each client: <<<"
            echo "attic-bootstrap: $TOKEN"
          '')
        ];

        networking.firewall.allowedTCPPorts = lib.optional cfg.server.openFirewall serverPort;
      })
    ]
  );
}
