#!/usr/bin/env python3
"""Generate .stignore files for Syncthing folders.

Each configured folder gets a generated .stignore containing:
  1. patterns translated from every .gitignore found inside the folder, and
  2. the shared global ignore list (syncthing/global-ignore in the nixos repo).

gitignore -> stignore translation notes:
  - gitignore: the *last* matching pattern wins; stignore: the *first* match
    wins. Patterns are therefore emitted in reverse order per file, and deeper
    .gitignore files are emitted before shallower ones, mirroring git's
    precedence rules. The global ignore list is emitted last (lowest
    precedence, like git's core.excludesFile) and is used verbatim since it is
    written in native stignore syntax.
  - gitignore patterns containing a slash are anchored to the directory of
    their .gitignore file; patterns without a slash match at any depth below
    it. stignore patterns are always relative to the folder root, so nested
    patterns get an explicit root-relative scope.
  - A trailing slash (dir-only marker) is dropped: ignoring the directory
    itself in stignore also covers its contents.
"""

import json
import os
import sys

# Directories never scanned for .gitignore files.
PRUNE_DIRS = {
    ".git",
    ".stfolder",
    ".stversions",
    ".direnv",
    "node_modules",
    "result",
}


def translate(line, rel_dir):
    """Translate one gitignore pattern into a list of stignore patterns."""
    line = line.rstrip()
    if not line or line.startswith("#"):
        return []

    negated = line.startswith("!")
    body = line[1:] if negated else line
    # Backslash escapes (\!foo, \#foo) mean the same thing in stignore.
    body = body.rstrip("/")
    if not body:
        return []

    prefix = "!" if negated else ""
    scope = "/" + rel_dir if rel_dir else ""

    if body.startswith("/"):
        # Anchored at the .gitignore's directory.
        return [f"{prefix}{scope}{body}"]
    if "/" in body:
        if body.startswith("**/"):
            # Matches at any depth below the .gitignore's directory,
            # including directly inside it.
            rest = body[3:]
            if scope:
                return [f"{prefix}{scope}/**/{rest}", f"{prefix}{scope}/{rest}"]
            return [f"{prefix}**/{rest}", f"{prefix}/{rest}"]
        # Relative to the .gitignore's directory.
        return [f"{prefix}{scope}/{body}"]
    # No slash: matches at any depth below the .gitignore's directory.
    if scope:
        return [f"{prefix}{scope}/{body}", f"{prefix}{scope}/**/{body}"]
    return [f"{prefix}{body}"]


def gitignore_sections(root):
    """Return [(rel_dir, [stignore patterns])] for each .gitignore, deepest first."""
    found = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in PRUNE_DIRS)
        if ".gitignore" in filenames:
            rel = os.path.relpath(dirpath, root)
            found.append("" if rel == "." else rel)
    # Deepest directories first: under stignore's first-match-wins rule this
    # mirrors git's precedence, where deeper .gitignore files override
    # shallower ones.
    found.sort(key=lambda d: (-(d.count(os.sep) + 1 if d else 0), d))

    sections = []
    for rel in found:
        try:
            with open(os.path.join(root, rel, ".gitignore"), encoding="utf-8", errors="replace") as f:
                lines = f.read().splitlines()
        except OSError:
            continue
        groups = [translate(line, rel) for line in lines]
        groups.reverse()  # gitignore: last match wins; stignore: first match wins
        patterns = [p for group in groups for p in group]
        if patterns:
            sections.append((rel, patterns))
    return sections


def build_stignore(root, use_gitignore, global_lines):
    lines = [
        "// This file is generated by the NixOS syncthing module - do not edit.",
        "// Sources: this folder's .gitignore files and syncthing/global-ignore from the nixos repo.",
        "// Regenerated at boot and every 15 minutes by the syncthing-ignores systemd service.",
        "",
    ]
    if use_gitignore:
        sections = gitignore_sections(root)
        if sections:
            lines.append("// --- .gitignore patterns (deeper files win) ---")
            for rel, patterns in sections:
                label = f"{rel}/.gitignore" if rel else ".gitignore"
                lines.append(f"// from {label}")
                lines.extend(patterns)
            lines.append("")
    lines.append("// --- global ignore patterns ---")
    lines.extend(global_lines)
    lines.append("")
    return "\n".join(lines)


def main():
    global_ignore_file, folders_json = sys.argv[1], sys.argv[2]
    with open(global_ignore_file, encoding="utf-8") as f:
        global_lines = f.read().splitlines()
    with open(folders_json, encoding="utf-8") as f:
        folders = json.load(f)

    failures = 0
    for folder in folders:
        root = folder["path"]
        try:
            os.makedirs(root, exist_ok=True)
            content = build_stignore(root, folder.get("gitignore", True), global_lines)
            target = os.path.join(root, ".stignore")
            try:
                with open(target, encoding="utf-8") as f:
                    if f.read() == content:
                        continue  # already up to date
            except OSError:
                pass
            with open(target, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"syncthing-ignores: wrote {target}")
        except OSError as e:
            print(f"syncthing-ignores: error processing {root}: {e}", file=sys.stderr)
            failures += 1
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
